//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cervejaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atendimento
    {
        public int AtendimentoId { get; set; }
        public Nullable<int> IdFuncionario { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> IdCompra { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Compra Compra { get; set; }
        public virtual Funcionario Funcionario { get; set; }
    }
}
