//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cervejaria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemEstoque
    {
        public int ItemEstoqueId { get; set; }
        public Nullable<int> IdProduto { get; set; }
        public Nullable<int> Quantidade { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
